[theme]
primaryColor = "#00F0FF"
backgroundColor = "#0B0F17"
secondaryBackgroundColor = "#131B2E"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
